version: '3'
services:
  zookeeper:
    image: zookeeper:3.4.9
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zookeeper:2888:3888
    volumes:
      - ./.data/zookeeper/data:/data
      - ./.data/zookeeper/datalog:/datalog
  kafka1:
    image: confluentinc/cp-kafka:5.3.0
    hostname: kafka1
    ports:
      - "9091:9091"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19091,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9091
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG4J_LOGGERS: org.apache.zookeeper=ERROR,org.apache.kafka=ERROR, kafka=ERROR, kafka.cluster=ERROR,kafka.controller=ERROR, kafka.coordinator=ERROR,kafka.log=ERROR,kafka.server=ERROR,kafka.zookeeper=ERROR,state.change.logger=ERROR
    volumes:
      - ./.data/kafka1/data:/var/lib/kafka/data
    depends_on:
      - zookeeper
  
  
  #kafdrop:
  #  image: obsidiandynamics/kafdrop
  #  restart: "no"
  #  ports:
  #    - "9000:9000"
    #environment:
    #  KAFKA_BROKERCONNECT: "kafka1:19091"
   # depends_on:
    #  - kafka1
   #   - kafka2
      


  spark:
    image: docker.io/bitnami/spark:3-debian-10
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
    volumes:
      - "./datasource:/var/data/stream-click-datasource" 
      
   

  spark-worker-1:
    image: docker.io/bitnami/spark:3-debian-10
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - "./datasource:/var/data/stream-click-datasource" 
    

  stream-click-event:
    build:
      context: ./stream-click-event
    #entrypoint: ["echo", "Service foo disabled"]
    volumes:
      - "./datasource:/var/data/stream-click-datasource" 
    depends_on:
      - spark
      - spark-worker-1
      - zookeeper
      - kafka1

  batch-click-event:
    build:
      context: ./batch-click-event
    #entrypoint: ["echo", "Service foo disabled"]
    volumes:
      - "./datasource:/var/data/stream-click-datasource" 
    depends_on:
      - spark
      - spark-worker-1
      - zookeeper
      - kafka1
    

      
    

  
